name: CI
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build native
      run: make native

    - name: Install cosmopolitan
      run: |
        # Avoid launching MZ exe in wine
        sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
        sudo chmod +x /usr/bin/ape
        sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
        sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

        mkdir cosmopolitan
        wget https://cosmo.zip/pub/cosmocc/cosmocc.zip
        unzip -d cosmopolitan cosmocc.zip

        # Make sure it works
        ./cosmopolitan/bin/make --version

    - name: Build cosmopolitan
      run: make COSMOCC=./cosmopolitan

    - name: Upload Cosmopolitan EXE
      uses: actions/upload-artifact@v6
      with:
        name: gpu_cfg_gen.exe
        path: gpu_cfg_gen.exe

    - name: Upload Linux
      uses: actions/upload-artifact@v6
      with:
        name: gpu_cfg_gen
        path: gpu_cfg_gen

  test:
    name: Native tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build native
      run: make native

    - name: Build native
      run: make native

    - name: Try generating
      run: |
        ./gpu_cfg_gen -t AMDR23 -s FRAKMBCP81331ASSY0 -p FRAGMASP81331PCB00 -o amd.bin
        ./gpu_cfg_gen -t NVGN22 -s FRAKMQCP41500ASSY0 -p FRAKHZCP41500PCB00 -o nvidia.bin
        ./gpu_cfg_gen -t NVGN22_NEWTHERMAL -s FRAKMQCP41500ASSY0 -p FRAKHZCP41500PCB00 -o nvidia.bin
        ./gpu_cfg_gen -t SSD -s FRAKMBCP81331ASSY0 -o ssd.bin
        ./gpu_cfg_gen -t PCIE -s FRAKMBCP81331ASSY0 -o pcie.bin

    - name: Try parsing
      run: |
        ./gpu_cfg_gen -i amd.bin
        ./gpu_cfg_gen -i nvidia.bin
        ./gpu_cfg_gen -i nvidia.bin
        ./gpu_cfg_gen -i ssd.bin
        ./gpu_cfg_gen -i pcie.bin
